Repository Progressive-Victory/crm-bot, pull requests merged in 2023-06, with the labels that each got.

#60 31 roles exporter
  locales/en-US/common.ftl
  locales/en-US/lead.ftl
  src/commands/chat/builders/lead.ts
  src/commands/chat/execution/lead/index.ts
  src/commands/chat/execution/lead/member-list.ts
  src/commands/chat/execution/lead/ping.ts
  src/commands/chat/execution/lead/region/role.ts
  src/commands/chat/execution/lead/vc/rename.ts
Labels: feature, priority: MEDIUM

#64 Eslint and formating allingment
  .eslintrc
  .gitattributes
  .husky/pre-commit
  .vscode/extensions.json
  .vscode/settings.json
  __tests__/test.ts
  locales/en-US/common.ftl
  package.json
  src/Client/Client.ts
  src/Client/Command.ts
  src/Client/Event.ts
  src/Client/Logger.ts
  src/Client/index.ts
  src/Client/interactionCreate.ts
  src/commands/chat/builders/lead.ts
  src/commands/chat/builders/metrics.ts
  src/commands/chat/execution/lead/index.ts
  src/commands/chat/execution/lead/member-list.ts
  src/commands/chat/execution/lead/ping.ts
  src/commands/chat/execution/lead/region/role.ts
  src/commands/chat/execution/lead/vc/rename.ts
  src/commands/chat/execution/metrics.ts
  src/commands/context_menu/deleteMessage.ts
  src/commands/context_menu/pinMessage.ts
  src/events/guildMemberAdd.ts
  src/events/guildMemberRemove.ts
  src/events/guildMemberUpdate.ts
  src/events/messageCreate.ts
  src/events/messageReactionAdd.ts
  src/events/ready.ts
  src/events/voiceStateUpdate.ts
  src/i18n/i18n.ts
  src/index.ts
  src/structures/Constants.ts
  src/structures/Database.ts
  src/structures/helpers.ts
  tsconfig.json
  yarn.lock
Labels: documentation, refactor

#72 Sme role (#13)
  .eslintrc
  .vscode/settings.json
  locales/en-US/sme.ftl
  src/commands/chat/builders/sme.ts
  src/commands/chat/execution/sme.ts
Labels: feature, priority: MEDIUM

#71 State struct standardized
  .eslintignore
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .huskyrc
  .prettierignore
  README.md
  assets/badge.png
  package.json
  src/commands/chat/builders/lead.ts
  src/commands/chat/execution/lead/index.ts
  src/commands/chat/execution/lead/member-list.ts
  src/commands/chat/execution/lead/ping.ts
  src/declarations/states.ts
  src/events/ready.ts
  src/i18n/i18n.ts
  src/structures/Constants.ts
  src/structures/helpers.ts
  src/structures/index.ts
  src/structures/states.ts
  yarn.lock
Labels: feature, priority: LOW, refactor

#77 lead regoin role command bug fix
  src/commands/chat/execution/lead/region/role.ts
  src/structures/index.ts
  src/structures/states.ts
Labels: bug

#76 lead regoin role command bug fix
  src/commands/chat/execution/lead/index.ts
  src/commands/chat/execution/lead/region/role.ts
  src/commands/context_menu/pinMessage.ts
  src/structures/index.ts
  src/structures/states.ts
Labels: bug, priority: HIGH
